// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGER.Domain.Enums;
using SIGER.Infrastructure.Persistence;

#nullable disable

namespace SIGER.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SIGERDbContext))]
    partial class SIGERDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_mesa", new[] { "Disponible", "FueraServicio", "Ocupada", "Reservada" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_orden", new[] { "Cancelada", "EnPreparacion", "Lista", "Pagada", "Pendiente", "Servida" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_pago", new[] { "Completado", "Fallido", "Pendiente", "Reembolsado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_reserva", new[] { "Cancelada", "Completada", "Confirmada", "Pendiente" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "metodo_pago", new[] { "Efectivo", "Otro", "Tarjeta", "Transferencia" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "origen_orden", new[] { "Desktop", "Web" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_orden", new[] { "Mesa", "ParaLlevar" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIGER.Domain.Entities.Audit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_auditoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accion");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidad");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_entidad");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("NewData")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_nuevos");

                    b.Property<string>("PreviousData")
                        .HasColumnType("jsonb")
                        .HasColumnName("datos_anteriores");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_auditoria_fecha_hora");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auditoria_id_usuario");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.HasKey("Id")
                        .HasName("pk_categoria");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_categoria_nombre");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_orden");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AccountRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("cuenta_solicitada");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas");

                    b.Property<DateTimeOffset>("OrderDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<OrderOrigin>("Origin")
                        .HasColumnType("origen_orden")
                        .HasColumnName("origen");

                    b.Property<OrderStatus>("Status")
                        .HasColumnType("estado_orden")
                        .HasColumnName("estado");

                    b.Property<long?>("TableId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_mesa");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<OrderType>("Type")
                        .HasColumnType("tipo_orden")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_orden");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_orden_id_cliente");

                    b.HasIndex("OrderDateTime")
                        .HasDatabaseName("ix_orden_fecha_hora");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orden_estado");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_orden_id_mesa");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_orden_id_usuario");

                    b.ToTable("orden", (string)null);
                });

            modelBuilder.Entity("SIGER.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nota");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_orden");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_producto");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("Id")
                        .HasName("pk_detalle_orden");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_detalle_orden_id_orden");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_detalle_orden_id_producto");

                    b.ToTable("detalle_orden", (string)null);
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto");

                    b.Property<PaymentMethod>("Method")
                        .HasColumnType("metodo_pago")
                        .HasColumnName("metodo");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_orden");

                    b.Property<DateTimeOffset>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<string>("Reference")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("referencia");

                    b.Property<PaymentStatus>("Status")
                        .HasColumnType("estado_pago")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id")
                        .HasName("pk_pago");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_pago_id_orden");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_pago_id_usuario");

                    b.ToTable("pago", (string)null);
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_producto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_url");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_producto");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_producto_id_categoria");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("ix_producto_disponible");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Promotion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_promocion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_descuento");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.HasKey("Id")
                        .HasName("pk_promocion");

                    b.HasIndex("IsActive", "StartDate", "EndDate")
                        .HasDatabaseName("ix_promocion_vigencia");

                    b.ToTable("promocion", (string)null);
                });

            modelBuilder.Entity("SIGER.Domain.Entities.PromotionProduct", b =>
                {
                    b.Property<long>("PromotionId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_promocion");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_producto");

                    b.HasKey("PromotionId", "ProductId")
                        .HasName("pk_promocion_producto");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_promocion_producto_id_producto");

                    b.ToTable("promocion_producto", (string)null);
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_reserva");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_personas");

                    b.Property<DateTimeOffset>("ReservationDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<ReservationStatus>("Status")
                        .HasColumnType("estado_reserva")
                        .HasColumnName("estado");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_mesa");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id")
                        .HasName("pk_reserva");

                    b.HasIndex("ReservationDateTime")
                        .HasDatabaseName("ix_reserva_fecha_hora");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_reserva_id_mesa");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reserva_id_usuario");

                    b.ToTable("reserva", (string)null);
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_rol");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_rol_nombre");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Table", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_mesa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ubicacion");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<TableStatus>("Status")
                        .HasColumnType("estado_mesa")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_mesa");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_mesa_numero");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_mesa_estado");

                    b.ToTable("mesa", (string)null);
                });

            modelBuilder.Entity("SIGER.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_rol");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("AuthUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_auth_user_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_correo");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_usuario_id_rol");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Audit", b =>
                {
                    b.HasOne("SIGER.Domain.Entities.User", "User")
                        .WithMany("Audits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_auditoria_usuario");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Order", b =>
                {
                    b.HasOne("SIGER.Domain.Entities.User", "Client")
                        .WithMany("ClientOrders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orden_cliente");

                    b.HasOne("SIGER.Domain.Entities.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orden_mesa");

                    b.HasOne("SIGER.Domain.Entities.User", "User")
                        .WithMany("CreatedOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orden_usuario");

                    b.Navigation("Client");

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("SIGER.Domain.Entities.Order", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_orden_orden");

                    b.HasOne("SIGER.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_detalle_orden_producto");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SIGER.Domain.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pago_orden");

                    b.HasOne("SIGER.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pago_usuario");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Product", b =>
                {
                    b.HasOne("SIGER.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_producto_categoria");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.PromotionProduct", b =>
                {
                    b.HasOne("SIGER.Domain.Entities.Product", "Product")
                        .WithMany("PromotionProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promocion_producto_producto");

                    b.HasOne("SIGER.Domain.Entities.Promotion", "Promotion")
                        .WithMany("PromotionProducts")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promocion_producto_promocion");

                    b.Navigation("Product");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("SIGER.Domain.Entities.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reserva_mesa");

                    b.HasOne("SIGER.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reserva_usuario");

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.User", b =>
                {
                    b.HasOne("SIGER.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Order", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("PromotionProducts");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Promotion", b =>
                {
                    b.Navigation("PromotionProducts");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.Table", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SIGER.Domain.Entities.User", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("ClientOrders");

                    b.Navigation("CreatedOrders");

                    b.Navigation("Payments");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
