<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIGER.Application\SIGER.Application.csproj" />
    <ProjectReference Include="..\SIGER.Domain\SIGER.Domain.csproj" />
  </ItemGroup>

</Project>
