-- Synthetic legacy fixture ONLY for a new, isolated local test database.
-- This is not a production schema/deployment script; do not run it on Supabase.
CREATE TYPE estado_mesa AS ENUM ('Disponible','Ocupada','Reservada','FueraServicio');
CREATE TYPE estado_orden AS ENUM ('Pendiente','EnPreparacion','Lista','Servida','Pagada','Cancelada');
CREATE TYPE estado_reserva AS ENUM ('Pendiente','Confirmada','Cancelada','Completada');
CREATE TYPE origen_orden AS ENUM ('Desktop','Web');
CREATE TYPE tipo_orden AS ENUM ('Mesa','ParaLlevar');
CREATE TYPE metodo_pago AS ENUM ('Efectivo','Tarjeta','Transferencia','Otro');
CREATE TYPE estado_pago AS ENUM ('Pendiente','Completado','Fallido','Reembolsado');
CREATE TABLE rol (id_rol bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre varchar(50) NOT NULL, descripcion varchar(250), estado boolean NOT NULL DEFAULT true);
CREATE TABLE usuario (id_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_rol bigint NOT NULL REFERENCES rol,
    auth_user_id uuid NOT NULL, nombre varchar(100) NOT NULL, apellido varchar(100) NOT NULL, email varchar(150) NOT NULL,
    telefono varchar(20), estado boolean NOT NULL DEFAULT true, fecha_creacion timestamptz NOT NULL DEFAULT now(), fecha_actualizacion timestamptz NOT NULL DEFAULT now());
CREATE TABLE mesa (id_mesa bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, numero int NOT NULL UNIQUE,
    capacidad int NOT NULL, estado estado_mesa NOT NULL DEFAULT 'Disponible', ubicacion varchar(100),
    fecha_creacion timestamptz NOT NULL DEFAULT now(), fecha_actualizacion timestamptz NOT NULL DEFAULT now(), version bigint NOT NULL DEFAULT 1);
CREATE TABLE categoria (id_categoria bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre varchar(100) NOT NULL,
    descripcion varchar(250), estado boolean NOT NULL DEFAULT true, fecha_creacion timestamptz NOT NULL DEFAULT now(), fecha_actualizacion timestamptz NOT NULL DEFAULT now());
CREATE TABLE producto (id_producto bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_categoria bigint NOT NULL REFERENCES categoria,
    nombre varchar(150) NOT NULL, descripcion varchar(500), precio numeric(12,2) NOT NULL, disponible boolean NOT NULL DEFAULT true,
    imagen_url text, fecha_creacion timestamptz NOT NULL DEFAULT now(), fecha_actualizacion timestamptz NOT NULL DEFAULT now(), version bigint NOT NULL DEFAULT 1);
CREATE TABLE reserva (id_reserva bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_usuario bigint NOT NULL REFERENCES usuario,
    id_mesa bigint NOT NULL REFERENCES mesa ON DELETE RESTRICT, fecha_hora timestamptz NOT NULL,
    cantidad_personas int NOT NULL CHECK (cantidad_personas > 0), estado estado_reserva NOT NULL DEFAULT 'Pendiente', observaciones varchar(500),
    fecha_creacion timestamptz NOT NULL DEFAULT now(), fecha_actualizacion timestamptz NOT NULL DEFAULT now());
CREATE TABLE orden (id_orden bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_usuario bigint NOT NULL REFERENCES usuario,
    id_cliente bigint REFERENCES usuario ON DELETE SET NULL, id_mesa bigint REFERENCES mesa,
    fecha_hora timestamptz NOT NULL DEFAULT now(), estado estado_orden NOT NULL DEFAULT 'Pendiente', origen origen_orden NOT NULL DEFAULT 'Desktop',
    tipo tipo_orden NOT NULL DEFAULT 'Mesa', total numeric(12,2) NOT NULL DEFAULT 0 CHECK (total >= 0), notas varchar(500),
    cuenta_solicitada boolean NOT NULL DEFAULT false, fecha_solicitud_cuenta timestamptz,
    fecha_actualizacion timestamptz NOT NULL DEFAULT now(), version bigint NOT NULL DEFAULT 1,
    CONSTRAINT chk_orden_tipo_mesa CHECK (tipo <> 'Mesa' OR id_mesa IS NOT NULL));
CREATE TABLE detalle_orden (id_detalle bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_orden bigint NOT NULL REFERENCES orden ON DELETE CASCADE,
    id_producto bigint NOT NULL REFERENCES producto, cantidad int NOT NULL CHECK (cantidad > 0), precio_unitario numeric(12,2) NOT NULL,
    subtotal numeric(12,2) NOT NULL, notas varchar(300));
CREATE TABLE pago (id_pago bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_orden bigint NOT NULL UNIQUE REFERENCES orden,
    id_usuario bigint NOT NULL REFERENCES usuario, monto numeric(12,2) NOT NULL, metodo metodo_pago NOT NULL, estado estado_pago NOT NULL,
    referencia varchar(100), fecha_pago timestamptz NOT NULL DEFAULT now(), fecha_actualizacion timestamptz NOT NULL DEFAULT now());
CREATE TABLE auditoria (id_auditoria bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_usuario bigint REFERENCES usuario ON DELETE SET NULL,
    accion varchar(100) NOT NULL, entidad varchar(100) NOT NULL, entidad_id bigint, datos_anteriores jsonb, datos_nuevos jsonb,
    direccion_ip inet, fecha_hora timestamptz NOT NULL);
CREATE INDEX idx_reserva_fecha ON reserva(fecha_hora);
CREATE INDEX idx_reserva_mesa ON reserva(id_mesa);
ALTER TABLE reserva ENABLE ROW LEVEL SECURITY;
ALTER TABLE orden ENABLE ROW LEVEL SECURITY;
INSERT INTO rol(nombre) VALUES ('Administrador');
INSERT INTO usuario(id_rol,auth_user_id,nombre,apellido,email) VALUES (1,'00000000-0000-0000-0000-000000000001','Test','Internal','test@example.invalid');
INSERT INTO mesa(numero,capacidad) VALUES (1,4);
INSERT INTO categoria(nombre) VALUES ('Activa');
INSERT INTO categoria(nombre,estado) VALUES ('Inactiva',false);
INSERT INTO producto(id_categoria,nombre,precio) VALUES (1,'Disponible',12.50),(2,'Categoria inactiva',20);
INSERT INTO producto(id_categoria,nombre,precio,disponible) VALUES (1,'No disponible',30,false);
-- Existing internal records must survive the script unchanged.
INSERT INTO reserva(id_usuario,id_mesa,fecha_hora,cantidad_personas,estado) VALUES (1,1,'2020-01-01Z',2,'Completada');
INSERT INTO orden(id_usuario,id_mesa,estado) VALUES (1,1,'Pagada');
